on: [push, pull_request]

name: Clippy check
jobs:
  clippy_check:
    name: Run Clippy
    runs-on: ubuntu-20.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: riscv32imac-unknown-none-elf
          components: clippy
      - run: cargo clippy --workspace --examples -- -Dwarnings
      - run: cargo clippy --workspace --examples --all-features -- -Dwarnings
